### ISSUE TITLE
Swap -> SEFI: memory leak

### ISSUE THREAD

**Issue by bitterbalpiraat** [enigmampc/EthereumBridgeBackend#8]
Forgive me if this is not the right place, but I'd like to provide feedback and suggest improvements. In the discord channels posts get quickly flooded by troubleshooting questions.

According to the console, jumping from SecretSwap to the SEFI tab results in a memory leak:
![swap-sefi](https://user-images.githubusercontent.com/16594338/113823299-c616f980-977e-11eb-96f5-6c3ad1e0dd51.JPG)

**Comment by Cashmaney** [comment]
Thanks for the report. We're aware of this issue. It's one of the next things on our list of fixes:)

**Comment by assafmo** [comment]
Fixed. Thanks man!
